 [Thu Aug 02 21:47:33 -0480] [runtime] [] "SH010101: Controller 'hello' is not a valid controller." 
 [Thu Aug 02 21:47:33 -0480] [runtime] [] "SH020101: Controller 'hello' not registered." 
 [Thu Aug 02 21:47:33 -0480] [runtime] [] "Error: SH000000: Fatal error, code not correct
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:9381)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:64)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@SH000000: Fatal error, code not correct" 
 [Thu Aug 02 21:47:33 -0480] [runtime] [] "Error: ErrorManager cannot determine your error
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:10883)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:65)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@ErrorManager cannot determine your error" 
 [Thu Aug 02 21:47:33 -0480] [runtime] [] "Error
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:23:53)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@" 
 [Thu Aug 02 21:47:33 -0480] [runtime] [] "Error: Error not defined
    at Function.RenderErrorAsHTML (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:11193)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:70)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@Error not defined" 
 [Thu Aug 02 21:47:33 -0480] [runtime] [] "SH010201: Invalid route rule: /. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 21:47:33 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{action}/{id}. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 21:47:33 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}/{id}#^#&#&$. The possible reason is:there are some invalid characters." 
 [Thu Aug 02 21:47:33 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}.... The possible reason is:invalid rule ending" 
 [Thu Aug 02 21:52:54 -0480] [runtime] [] "SH010101: Controller 'hello' is not a valid controller." 
 [Thu Aug 02 21:52:54 -0480] [runtime] [] "SH020101: Controller 'hello' not registered." 
 [Thu Aug 02 21:52:54 -0480] [runtime] [] "Error: SH000000: Fatal error, code not correct
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:9381)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:64)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@SH000000: Fatal error, code not correct" 
 [Thu Aug 02 21:52:54 -0480] [runtime] [] "Error: ErrorManager cannot determine your error
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:10883)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:65)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@ErrorManager cannot determine your error" 
 [Thu Aug 02 21:52:54 -0480] [runtime] [] "Error
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:23:53)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@" 
 [Thu Aug 02 21:52:54 -0480] [runtime] [] "Error: Error not defined
    at Function.RenderErrorAsHTML (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:11193)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:70)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@Error not defined" 
 [Thu Aug 02 21:52:54 -0480] [runtime] [] "SH010201: Invalid route rule: /. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 21:52:54 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{action}/{id}. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 21:52:54 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}/{id}#^#&#&$. The possible reason is:there are some invalid characters." 
 [Thu Aug 02 21:52:54 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}.... The possible reason is:invalid rule ending" 
 [Thu Aug 02 21:53:20 -0480] [runtime] [] "SH010101: Controller 'hello' is not a valid controller." 
 [Thu Aug 02 21:53:20 -0480] [runtime] [] "SH020101: Controller 'hello' not registered." 
 [Thu Aug 02 21:53:20 -0480] [runtime] [] "Error: SH000000: Fatal error, code not correct
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:9381)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:64)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@SH000000: Fatal error, code not correct" 
 [Thu Aug 02 21:53:20 -0480] [runtime] [] "Error: ErrorManager cannot determine your error
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:10883)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:65)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@ErrorManager cannot determine your error" 
 [Thu Aug 02 21:53:20 -0480] [runtime] [] "Error
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:23:53)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@" 
 [Thu Aug 02 21:53:20 -0480] [runtime] [] "Error: Error not defined
    at Function.RenderErrorAsHTML (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:11193)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:70)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@Error not defined" 
 [Thu Aug 02 21:53:20 -0480] [runtime] [] "SH010201: Invalid route rule: /. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 21:53:20 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{action}/{id}. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 21:53:20 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}/{id}#^#&#&$. The possible reason is:there are some invalid characters." 
 [Thu Aug 02 21:53:20 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}.... The possible reason is:invalid rule ending" 
 [Thu Aug 02 21:56:54 -0480] [runtime] [] "SH010101: Controller 'hello' is not a valid controller." 
 [Thu Aug 02 21:56:54 -0480] [runtime] [] "SH020101: Controller 'hello' not registered." 
 [Thu Aug 02 21:56:54 -0480] [runtime] [] "Error: SH000000: Fatal error, code not correct
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:9013)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:64)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@SH000000: Fatal error, code not correct" 
 [Thu Aug 02 21:56:54 -0480] [runtime] [] "Error: ErrorManager cannot determine your error
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:10515)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:65)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@ErrorManager cannot determine your error" 
 [Thu Aug 02 21:56:54 -0480] [runtime] [] "Error
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:23:53)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@" 
 [Thu Aug 02 21:56:54 -0480] [runtime] [] "Error: Error not defined
    at Function.RenderErrorAsHTML (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:10825)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:70)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@Error not defined" 
 [Thu Aug 02 21:56:54 -0480] [runtime] [] "SH010201: Invalid route rule: /. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 21:56:54 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{action}/{id}. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 21:56:54 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}/{id}#^#&#&$. The possible reason is:there are some invalid characters." 
 [Thu Aug 02 21:56:54 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}.... The possible reason is:invalid rule ending" 
 [Thu Aug 02 21:57:17 -0480] [runtime] [] "SH010101: Controller 'hello' is not a valid controller." 
 [Thu Aug 02 21:57:17 -0480] [runtime] [] "SH020101: Controller 'hello' not registered." 
 [Thu Aug 02 21:57:17 -0480] [runtime] [] "Error: SH000000: Fatal error, code not correct
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:9005)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:64)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@SH000000: Fatal error, code not correct" 
 [Thu Aug 02 21:57:17 -0480] [runtime] [] "Error: ErrorManager cannot determine your error
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:10507)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:65)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@ErrorManager cannot determine your error" 
 [Thu Aug 02 21:57:17 -0480] [runtime] [] "Error
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:23:53)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@" 
 [Thu Aug 02 21:57:17 -0480] [runtime] [] "Error: Error not defined
    at Function.RenderErrorAsHTML (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:10817)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:70)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@Error not defined" 
 [Thu Aug 02 21:57:17 -0480] [runtime] [] "SH010201: Invalid route rule: /. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 21:57:17 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{action}/{id}. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 21:57:17 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}/{id}#^#&#&$. The possible reason is:there are some invalid characters." 
 [Thu Aug 02 21:57:17 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}.... The possible reason is:invalid rule ending" 
 [Thu Aug 02 22:02:29 -0480] [runtime] [] "SH010101: Controller 'hello' is not a valid controller." 
 [Thu Aug 02 22:02:29 -0480] [runtime] [] "SH020101: Controller 'hello' not registered." 
 [Thu Aug 02 22:02:29 -0480] [runtime] [] "Error: SH000000: Fatal error, code not correct
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:9005)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:64)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@SH000000: Fatal error, code not correct" 
 [Thu Aug 02 22:02:29 -0480] [runtime] [] "Error: ErrorManager cannot determine your error
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:10507)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:65)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@ErrorManager cannot determine your error" 
 [Thu Aug 02 22:02:29 -0480] [runtime] [] "Error
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:23:53)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@" 
 [Thu Aug 02 22:02:29 -0480] [runtime] [] "Error: Error not defined
    at Function.RenderErrorAsHTML (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:10817)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:70)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@Error not defined" 
 [Thu Aug 02 22:02:30 -0480] [runtime] [] "SH010201: Invalid route rule: /. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 22:02:30 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{action}/{id}. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 22:02:30 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}/{id}#^#&#&$. The possible reason is:there are some invalid characters." 
 [Thu Aug 02 22:02:30 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}.... The possible reason is:invalid rule ending" 
 [Thu Aug 02 22:02:54 -0480] [runtime] [] "SH010101: Controller 'hello' is not a valid controller." 
 [Thu Aug 02 22:02:54 -0480] [runtime] [] "SH020101: Controller 'hello' not registered." 
 [Thu Aug 02 22:02:54 -0480] [runtime] [] "Error: SH000000: Fatal error, code not correct
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:9005)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:64)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@SH000000: Fatal error, code not correct" 
 [Thu Aug 02 22:02:54 -0480] [runtime] [] "Error: ErrorManager cannot determine your error
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:10507)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:65)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@ErrorManager cannot determine your error" 
 [Thu Aug 02 22:02:54 -0480] [runtime] [] "Error
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:23:53)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@" 
 [Thu Aug 02 22:02:54 -0480] [runtime] [] "Error: Error not defined
    at Function.RenderErrorAsHTML (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:10817)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:70)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@Error not defined" 
 [Thu Aug 02 22:02:54 -0480] [runtime] [] "SH010201: Invalid route rule: /. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 22:02:54 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{action}/{id}. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 22:02:54 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}/{id}#^#&#&$. The possible reason is:there are some invalid characters." 
 [Thu Aug 02 22:02:54 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}.... The possible reason is:invalid rule ending" 
 [Thu Aug 02 22:04:19 -0480] [runtime] [] "SH010101: Controller 'hello' is not a valid controller." 
 [Thu Aug 02 22:04:19 -0480] [runtime] [] "SH020101: Controller 'hello' not registered." 
 [Thu Aug 02 22:04:19 -0480] [runtime] [] "Error: SH000000: Fatal error, code not correct
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:9005)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:64)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@SH000000: Fatal error, code not correct" 
 [Thu Aug 02 22:04:19 -0480] [runtime] [] "Error: ErrorManager cannot determine your error
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:10507)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:65)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@ErrorManager cannot determine your error" 
 [Thu Aug 02 22:04:19 -0480] [runtime] [] "Error
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:23:53)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@" 
 [Thu Aug 02 22:04:19 -0480] [runtime] [] "Error: Error not defined
    at Function.RenderErrorAsHTML (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:10817)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:70)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@Error not defined" 
 [Thu Aug 02 22:04:19 -0480] [runtime] [] "SH010201: Invalid route rule: /. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 22:04:19 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{action}/{id}. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 22:04:19 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}/{id}#^#&#&$. The possible reason is:there are some invalid characters." 
 [Thu Aug 02 22:04:19 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}.... The possible reason is:invalid rule ending" 
 [Thu Aug 02 22:05:43 -0480] [runtime] [] "SH010101: Controller 'hello' is not a valid controller." 
 [Thu Aug 02 22:05:43 -0480] [runtime] [] "SH020101: Controller 'hello' not registered." 
 [Thu Aug 02 22:05:43 -0480] [runtime] [] "Error: SH000000: Fatal error, code not correct
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:9005)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:15:64)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@SH000000: Fatal error, code not correct" 
 [Thu Aug 02 22:05:43 -0480] [runtime] [] "Error: ErrorManager cannot determine your error
    at Function.RenderError (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:10507)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:19:65)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@ErrorManager cannot determine your error" 
 [Thu Aug 02 22:05:43 -0480] [runtime] [] "Error
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:23:53)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@" 
 [Thu Aug 02 22:05:43 -0480] [runtime] [] "Error: Error not defined
    at Function.RenderErrorAsHTML (/home/davidy/Documents/Personal/repositories/serverhub-mvc/dist/lib/core/error/error.js:1:10817)
    at expect (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:41)
    at Proxy.assertThrows (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/core/assertions.js:2554:7)
    at Proxy.methodWrapper (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Context.<anonymous> (/home/davidy/Documents/Personal/repositories/serverhub-mvc/test/unit-test/modules/error/index.js:27:70)
    at callFnAsync (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:406:21)
    at Test.Runnable.run (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runnable.js:353:7)
    at Runner.runTest (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:446:10)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:564:12
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:360:14)
    at /home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:370:7
    at next (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/home/davidy/Documents/Personal/repositories/serverhub-mvc/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)@Error@Error not defined" 
 [Thu Aug 02 22:05:43 -0480] [runtime] [] "SH010201: Invalid route rule: /. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 22:05:43 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{action}/{id}. The possible reason is:controller and action fields are required" 
 [Thu Aug 02 22:05:43 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}/{id}#^#&#&$. The possible reason is:there are some invalid characters." 
 [Thu Aug 02 22:05:43 -0480] [runtime] [] "SH010201: Invalid route rule: /v1/{controller}/{action}.... The possible reason is:invalid rule ending" 
